spring:
  profiles:
    active: dev
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
#  aop:
#    proxy-target-class: true
#    auto: true
#  datasource:
#    druid:
#        db1:
#          username: root
#          password: wangchuan116256
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://cdb-plkru6h8.cd.tencentcdb.com:10004/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
#          initialSize: 5
#          minIdle: 5
#          maxActive: 20
#        db2:
#          username: root
#          password: wangchuan116256
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://cdb-plkru6h8.cd.tencentcdb.com:10004/springboot_vue?useUnicode=true&characterEncoding=utf-8&useSSL=false
#          initialSize: 5
#          minIdle: 5
#          maxActive: 20
#mybatis-plus:
## 如果是放在src/main/java目录下 classpath:/com/yourPackage/*/mapper/*Mapper.xml
## 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  config-location: classpath:mapper/*Mapper.xml
## 实体扫描，多个package用逗号或者分号隔开
#  type-aliases-package: com.xxx.myspringboot.demo.model.*
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新Mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 4
#    logic-not-delete-value: 0
#    configuration:
#      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#      map-underscore-to-camel-case: true
#      cache-enabled: false
#      #配置JdbcTypeForNull, oracle数据库必须配置
#      jdbc-type-for-null: 'null'


#wangchuan:
#  name: 王川
#  age: 23
